name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Ensure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          # Use npm ci for reproducible builds when package-lock.json exists, otherwise fall back to npm install
          if test -f package-lock.json; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

      - name: Install Python deps for tools (if needed)
        run: |
          python -m pip install --upgrade pip
          # If running on Python <3.11, ensure `toml` is available; otherwise tomllib will be used.
          pip install --no-deps toml || true

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release